version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: local-db
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
      MYSQL_DATABASE: local_database
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    command:
      - --character-set-server=UTF8MB4
      - --collation-server=UTF8MB4_UNICODE_CI